### PR TITLE
v5 release

### PR DESCRIPTION
**Pull request by mrmckeb**
This contains all agreed changes for the V5 release.

This PR also contains a fix from #67 (closes #67).

### CODE REVIEW

**Review by codybrouwers — APPROVED** [review]
Looks good!

**Comment by joulev** [comment]
@mrmckeb Maybe `typescript@5` should also be added to `peerDependencies`?

**Comment by mrmckeb** [comment]
@joulev, unless I missed something, this should still work with older TS versions. From 4.2.4 I think.

However, we have from 4.8 already set.

**Comment by joulev** [comment]
@mrmckeb I meant this should also work with TypeScript 5 too. Currently the peer dependency is set at `typescript@^4.8.0` so if I use TypeScript 5 I will get peer dependency not match warnings/errors:

```
 WARN  Issues with peer dependencies found
.
└─┬ @vercel/style-guide 5.0.0-canary.1
  └── ✕ unmet peer typescript@^4.8.0: found 5.2.2
```

Things still work well with TypeScript 5 as far as I see so maybe we should allow v5 in the peer dependency declaration too.

**Comment by mrmckeb** [comment]
Good point, thanks - we'll release a patch to fix peer deps.

**Pull request merged**
